[package]
name = "shape-engine-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
rand.workspace = true
thiserror.workspace = true
